"""Alert model — Couche 4 (Corrélation & Réponse).

An Alert is created by the correlation task when one or more IoCs match
entries in a client's Elasticsearch log index.

Correlation flow:
  1. `tasks/correlation.py` queries Elasticsearch using IoC values
     (IP, domain, hash, URL…) against the client's normalised log index.
  2. On a hit:
       a. Alert row is created with severity, title, raw_log_ref
       b. alert_iocs rows link the triggering IoCs
       c. Asset is looked up by hostname / IP → alert.asset_id set
       d. Threat is inherited from the IoC's threat grouping
  3. The Shuffle SOAR playbook is triggered:
       a. Cortex enriches the IoCs (VirusTotal, Shodan, AbuseIPDB)
       b. TheHive v4 case is created → thehive_case_id stored here
       c. SOC analyst is notified

Analyst workflow (AlertStatus transitions):
  open → investigating  (analyst picks up the alert)
  investigating → resolved      (threat confirmed, remediated)
  investigating → false_positive (correlation hit deemed benign)

`mitre_technique_id` maps the alert to a single primary ATT&CK technique
so the Navigator heatmap reflects real detections, not just IoC mappings.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Enum as SqlEnum, ForeignKey, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import Uuid

from backend.models.associations import alert_iocs
from backend.models.base import Base
from backend.models.enums import AlertStatus, Severity


class Alert(Base):
    __tablename__ = "alerts"

    # ------------------------------------------------------------------
    # Identity
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # ------------------------------------------------------------------
    # Ownership & scope
    # ------------------------------------------------------------------
    client_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("clients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="The MSSP client whose environment triggered this alert",
    )
    hunting_job_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("hunting_jobs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="The correlation job that produced this alert",
    )
    asset_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("assets.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="The specific client asset (host) where the IoC was observed",
    )
    threat_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("threats.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Threat cluster this alert belongs to — inherited from triggering IoCs",
    )

    # ------------------------------------------------------------------
    # Classification
    # ------------------------------------------------------------------
    severity: Mapped[Severity] = mapped_column(
        SqlEnum(Severity, name="severity_enum"),
        nullable=False,
        index=True,
        comment=(
            "Computed from: max(IoC severity) × asset criticality weight. "
            "Used for sorting on the analyst dashboard."
        ),
    )
    status: Mapped[AlertStatus] = mapped_column(
        SqlEnum(AlertStatus, name="alert_status_enum"),
        nullable=False,
        default=AlertStatus.OPEN,
        index=True,
    )

    # ------------------------------------------------------------------
    # Content
    # ------------------------------------------------------------------
    title: Mapped[str] = mapped_column(
        String(500), nullable=False,
        comment=(
            "Auto-generated by the correlation task. "
            "Pattern: '[IoC type] [value] detected on [hostname]'"
        ),
    )
    description: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        comment="Detailed context: which log field matched, surrounding log lines, enrichment",
    )
    raw_log_ref: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        comment="Elasticsearch document _id or Kibana deep-link for the matching log entry",
    )

    # ------------------------------------------------------------------
    # ATT&CK mapping
    # ------------------------------------------------------------------
    mitre_technique_id: Mapped[str | None] = mapped_column(
        String(50), nullable=True,
        comment=(
            "Primary MITRE ATT&CK technique ID for this detection. "
            "e.g. 'T1566.001' (Spearphishing Attachment). "
            "Feeds the Navigator heatmap to show real detection coverage."
        ),
    )

    # ------------------------------------------------------------------
    # External case management (TheHive)
    # ------------------------------------------------------------------
    thehive_case_id: Mapped[str | None] = mapped_column(
        String(255), nullable=True,
        comment="TheHive v4 case ID created by the Shuffle SOAR playbook",
    )

    # ------------------------------------------------------------------
    # Analyst validation
    # ------------------------------------------------------------------
    validated_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="SOC analyst who changed status to resolved or false_positive",
    )
    validated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ------------------------------------------------------------------
    # Audit
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Automatically updated by the ORM on every status change",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    client: Mapped["Client"] = relationship(  # noqa: F821
        "Client", back_populates="alerts", lazy="joined"
    )
    hunting_job: Mapped["HuntingJob"] = relationship(  # noqa: F821
        "HuntingJob", back_populates="alerts", lazy="joined"
    )
    asset: Mapped["Asset"] = relationship(  # noqa: F821
        "Asset", back_populates="alerts", lazy="joined"
    )
    threat: Mapped["Threat"] = relationship(  # noqa: F821
        "Threat", back_populates="alerts", lazy="joined"
    )
    validated_by_user: Mapped["User"] = relationship(  # noqa: F821
        "User", foreign_keys=[validated_by], lazy="joined"
    )
    # IoCs that triggered this alert — essential for analyst triage detail page
    iocs: Mapped[list["IoC"]] = relationship(  # noqa: F821
        "IoC", secondary=alert_iocs, back_populates="alerts", lazy="selectin"
    )
