"""Report model — Couche 6 (Présentation & Reporting).

A Report is a PDF document generated by WeasyPrint and stored in MinIO.
It summarises the results of a threat hunting operation for a client.

Generation flow:
  1. SOC Admin requests a report via `POST /admin/reports/generate`
  2. FastAPI creates a Report row with status=GENERATING
  3. A `report_gen` Celery task is dispatched
  4. The task:
       a. Queries PostgreSQL for IoCs, alerts, assets, threats in scope
       b. Renders the Jinja2 HTML template with the data
       c. WeasyPrint converts HTML/CSS → PDF bytes
       d. PDF is uploaded to MinIO under `reports/{client_id}/{report_id}.pdf`
       e. Report.minio_object_key + file_size_bytes are saved
       f. Report.status → READY
  5. The frontend is notified via WebSocket push
  6. Client portal shows a download button → `GET /reports/{id}/download`
     returns a pre-signed MinIO URL (valid 1 hour)

Report types:
  threat_hunt       : full technical report (IoC table, timeline, ATT&CK heatmap)
  executive_summary : KPI-focused, no raw IoC data — for CISO / management
  ioc_report        : flat IoC list with type / severity / TLP / description
  incident          : post-incident forensic report tied to a TheHive case
"""

import uuid
from datetime import date, datetime

from sqlalchemy import BigInteger, Date, DateTime, Enum as SqlEnum, ForeignKey, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import Uuid

from backend.models.base import Base
from backend.models.enums import ReportStatus, ReportType


class Report(Base):
    __tablename__ = "reports"

    # ------------------------------------------------------------------
    # Identity
    # ------------------------------------------------------------------
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # ------------------------------------------------------------------
    # Ownership & scope
    # ------------------------------------------------------------------
    client_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("clients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="The client this report was generated for",
    )
    hunting_job_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("hunting_jobs.id", ondelete="SET NULL"),
        nullable=True,
        comment="The hunt or correlation job whose results are summarised in this report",
    )
    generated_by: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        comment="SOC analyst who requested generation",
    )

    # ------------------------------------------------------------------
    # Classification
    # ------------------------------------------------------------------
    report_type: Mapped[ReportType] = mapped_column(
        SqlEnum(ReportType, name="report_type_enum"),
        nullable=False,
        comment="Determines which Jinja2 template is rendered",
    )
    title: Mapped[str] = mapped_column(
        String(500), nullable=False,
        comment="Auto-generated or overridden by analyst — appears on the PDF cover page",
    )

    # ------------------------------------------------------------------
    # Content period
    # ------------------------------------------------------------------
    period_start: Mapped[date | None] = mapped_column(
        Date, nullable=True,
        comment="Start of the time window covered by this report (inclusive)",
    )
    period_end: Mapped[date | None] = mapped_column(
        Date, nullable=True,
        comment="End of the time window covered by this report (inclusive)",
    )

    # ------------------------------------------------------------------
    # Storage (MinIO)
    # ------------------------------------------------------------------
    status: Mapped[ReportStatus] = mapped_column(
        SqlEnum(ReportStatus, name="report_status_enum"),
        nullable=False,
        default=ReportStatus.GENERATING,
        index=True,
        comment="Generation lifecycle — frontend polls this until READY",
    )
    minio_object_key: Mapped[str | None] = mapped_column(
        String(512), nullable=True,
        comment=(
            "Full MinIO object path after upload. "
            "Pattern: reports/{client_id}/{report_id}.pdf. "
            "Used to generate pre-signed download URLs."
        ),
    )
    file_size_bytes: Mapped[int | None] = mapped_column(
        BigInteger, nullable=True,
        comment="PDF file size — displayed in the client portal download list",
    )

    # ------------------------------------------------------------------
    # Audit
    # ------------------------------------------------------------------
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    client: Mapped["Client"] = relationship(  # noqa: F821
        "Client", back_populates="reports", lazy="joined"
    )
    hunting_job: Mapped["HuntingJob"] = relationship(  # noqa: F821
        "HuntingJob", back_populates="reports", lazy="joined"
    )
    generated_by_user: Mapped["User"] = relationship(  # noqa: F821
        "User", foreign_keys=[generated_by], lazy="joined"
    )
